---
title: '2019-05-15'
output: html_document
---

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2
```
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```
```{r}
b[[3]] <-FALSE
b[[5]] <-"7"
b
```
```{r}
b$元素3 <- TRUE
b$元素5<-"7"
b
```
```{r}
b$新元素 <-"New"
b
```
```{r}
b[["新元素A"]] <- c("1","2","3")
b
```
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
```{r}
library(lubridate)
exData3[["期間"]]
exData3[["期間"]] <-ymd(exData3[["期間"]])
class(exData3$期間)

```
```{r}
exData3$isAsiaCrisis <- (exData3[["期間"]] >=ymd("1997-06-01") & exData3[["期間"]] <=ymd("1998-12-01"))
exData3
```
```{r}
logiAsiaCrisis <-exData3$isAsiaCrisis
exData3[logiAsiaCrisis,]
```
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```
```{r}
names(transcriptDataFinal)
```
```{r}
test <-transcriptDataFinal$學號 =="92aS67fee"
transcriptDataFinal[test,]
```
```{r}
utility_cobb_douglass2 <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```

```{r}
utility_cobb_douglass2(1,2) # 使用預設值
utility_cobb_douglass2(1,2,0.5,0.8) # 自定參數值
```
```{r}
practice <- function(x,.alpha){
  practicevalue <- x+.alpha
  return(practicevalue)
}
```

```{r}
practice(1,2)
```
```{r}
supply_fun <-function(.a,.b,.P){
  Qs <-.a+.b*.P
  return(Qs)
}
```
```{r}
demand_fun <-function(.c,.d,.P){
  Qd <-.c-.d*.P
  return(Qd)
}
```
```{r}
demand_fun(5,1,1)
supply_fun(0,1,1)
```
```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

