---
title: '2019-06-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
```

## R Markdown

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
for (i in seq_along(gmailAddress)) {
  if (!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGamilAddress <-str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <-correctGamilAddress}
  }
```

```{r}
gmailAddress
```
```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

```{r}
for (i in seq_along(commitHistory)) {
  print(commitHistory[[i]][["commit"]][["author"]][["name"]])
  print(commitHistory[[i]][["commit"]][["committer"]][["name"]])
  print(commitHistory)[[i]][["commit"]][["committer"]][["date"]]
}
```

```{r}
for(i in seq_along(commitHistory)){
  (commitHistory[[i]][["commit"]][["author"]][["name"]]==
     commitHistory[[i]][["commit"]][["committer"]][["name"]]) ->
    logiResult
  print(logiResult)  
}
```

```{r}
for (i in seq_along(commitHistory)){
  print(
    commitHistory[[i]][["commit"]][["author"]][["name"]] == commitHistory[[i]][["commit"]][["committer"]][["name"]]
  )
}1
```

```{r}
saveCharacter <- vector("character",5)
saveCharacter

saveNumeric <- vector("numeric",5)
saveNumeric

saveLogical <- vector("logical",5)
saveLogical

saveList <- vector("list",5)
saveList
```
```{r}
# 把"你好"存在saveCharacter第3個位置
saveCharacter # 儲存前
saveCharacter[[3]] <- "你好"
saveCharacter # 儲存後

# 把 72.3 存在saveNumeric第3個位置
saveNumeric # 儲存前
saveNumeric[[3]] <- 72.3
saveNumeric # 儲存後

# 把 TRUE 存在saveLogical第3個位置
saveLogical # 儲存前
saveLogical[[3]] <- TRUE
saveLogical # 儲存後

# 把 list(姓名="小明",電話="02-86741111") 存在saveList第3個位置
saveList # 儲存前
saveList[[3]] <- list(姓名="小明",電話="02-86741111")
saveList # 儲存後
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # sequence_source
saveGPAs <- vector("numeric",length(studentIds)) # saveContainer
for(i in seq_along(studentIds)){
  saveGPAs[[i]] <- gpa_fun(studentIds[[i]])
}
```

```{r}

```


