---
title: '2019-05-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
library(lubridate)
```
```{r}
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical
ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],tz="Asia/Taipei") ->tpdateTime
invoiceList$UTC時間[tpLogical] <-with_tz(tpdateTime,tzone="UTC")
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent

subSample <- transcriptDataFinal[logiChosenStudent,]

sum(subSample$學期成績*subSample$學分數)/
  sum(subSample$學分數) -> GPA
```

```{r}
#請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示。#
#ymd_hms_tzChange(input,fromTzone,toTzone)

ymd_hms_tzChange <- function(ny,fromTzone,toTzone){
  dateTime <-ymd_hms(ny,tz=fromTzone)
  toTzone <-with_tz(dateTime,tzone=toTzone)
  return(toTzone)
  }
```
```{r}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```
```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates

twDates
```

```{r}
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))

yyyymmdd
```
```{r}
date_convert_twYM0 <-function(twDates){
  x1 <-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  x2 <-str_extract(twDates,"[:digit:]+(?=月)")
  x <-ymd(str_c(x1,x2,"01",sep="-"))
  return(x)
}
```

```{r}
date_convert_twYM <- function(twDates){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
  }
```

```{r}
date_convert_twYM1 <- function(twDates,num="01"){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,num,sep="-"))
  return(yyyymmdd)
  }
```

```{r}
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates_New

twDates_New
date_convert_twYM1(twDates_New)
date_convert_twYM1(twDates_New,num="04")
```

## R Markdown

