---
title: "0327practice "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(lubridate)
```

```{r}
Sys.timezone()
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
class(dtObject)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
```

```{r}
typeof(twDateTime)
as.double(twDateTime)
```

```{r}
twDateTime <- mdy_hms("3/14/2019 8:18:47",tz="Asia/Taipei")
```

```{r}
today <- ymd("2018-09-11")
```

```{r}
today1 <- mdy("March 3, 2019")
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```

```{r}
a+b
b-a
a/b
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
a+aL
a+bL
aL+bL
```
```{r}
class(a+aL)
class(a/b)
class(aL+bL)
```
```{r}
a+5
```
```{r}
a^b
a %% b
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```
```{r}
twDateTime+1
```
```{r}
datetime1 <- ymd("2019-08-11")
datetime2 <- ymd("2000-02-01")
```

```{r}
datetime1-datetime2
```
```{r}
datetime1 + years(1)
datetime2 + dyears(1)
```
```{r}
startingDate <- ymd("2000-02-17")
```
```{r}
startingDate + dyears(1)
```
```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```
```{r}
x == y
x <= y
x < y
x != y
x2 == y2
```
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```
```{r}
x3 == y3
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
y5 %in% x5
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```
```{r}
x2 %in% y2
is.na(x2)
```
```{r}
sum(x2)
```



