---
title: "2019-04-04practice"
output: html_document
---
```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3 == y3
```

```{r}
x3 != y3
```

```{r}
x3 == y3
!(x3 == y3)
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

```{r}
head(currency)
```

```{r}
currency <- as.factor(currency)
class(currency)
```

```{r}
levels(currency)
```
```{r}
length(levels(currency))
```
```{r}
head(currency)
levels(currency)
```

```{r}
currency2 <- c("日元","美元","日元")
currency2
```
```{r}
currency2 == "日元"
```
```{r}
sum(currency2 == "日元")
```
```{r}
head(currency)
(currency == "日圓JPY/USD")
```
```{r}
sum(currency == "日圓JPY/USD")
```

```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
```
```{r}
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5=="女"
```

```{r}
!(y5=="女")
```

```{r}
x5 %in% greatTaipei
y5=="女"
(x5 %in% greatTaipei) & (y5=="女")

```
```{r}
which((x5 %in% greatTaipei) & (y5 =="女"))
```
```{r}
(x5 %in% greatTaipei)
(y5=="女")
(x5 %in% greatTaipei) | (y5=="女")
```
```{r}
which((x5 %in% greatTaipei) | (y5=="女"))
```
```{r}
(x5 %in% greatTaipei)
(y5=="女")
xor(x5 %in% greatTaipei, y5=="女")
```
```{r}
which(xor(x5 %in% greatTaipei, y5=="女"))
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```
```{r}
head(date)
```
```{r}
library(lubridate)
date <- ymd(date)
```
```{r}
class(date)
```

```{r}
after19800801 <-
  date >= ymd("1980-08-01")
after19800801
```

```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head( date >= ymd("1980-08-01"))
```

```{r}
class(after19800801)
sum(after19800801)
```

```{r}
head(currency == "歐元USD/EUR")
```
```{r}
Euro <- currency == "歐元USD/EUR"
sum(Euro)
```

```{r}
exchangeRateNA <-
  is.na(exchangeRate)
sum(exchangeRateNA)
```

```{r}
NotNA <- !is.na(exchangeRate)
Euro <- currency == "歐元USD/EUR"
```

```{r}
satisfy <- NotNA & Euro
sum(satisfy)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```
1.
```{r}
head(major)
majoreco <- major =="經濟學系"
sum(majoreco)
```
2.
```{r}
student0 <- studentID == "5bdS6977b"
sum(student0)
```
3.
```{r}
grade0 <- (grade >=60)
sum(grade0 & student0)
```
4.
```{r}
courseType0 <- courseType == "選"
sum(majoreco & courseType0)
```
5.
```{r}
courseType1 <- majoreco & courseType == "必"
grade1 <- grade <60
sum(majoreco & grade1 & courseType1 )/sum(majoreco & courseType1)

```

